# Generated by Django 4.0.6 on 2023-10-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciclo',
            old_name='nome',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='tese',
            name='ciclo_estudos',
        ),
        migrations.AddField(
            model_name='tese',
            name='cursos',
            field=models.ManyToManyField(related_name='cursos', to='teses.curso'),
        ),
    ]
