# Generated by Django 4.0.6 on 2023-10-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0002_rename_nome_ciclo_numero_remove_tese_ciclo_estudos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='teses.ciclo'),
        ),
    ]
