# Generated by Django 4.0.6 on 2023-10-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0003_curso_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='tese',
        ),
        migrations.AddField(
            model_name='autor',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='teses',
            field=models.ManyToManyField(related_name='autores', to='teses.tese'),
        ),
        migrations.AddField(
            model_name='tese',
            name='github',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tese',
            name='numero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tese',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
