# Generated by Django 4.0.6 on 2023-10-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0004_remove_autor_tese_autor_numero_autor_teses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tese',
            name='nota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
