# Generated by Django 4.0.6 on 2023-10-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0006_tese_autores_delete_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tese',
            old_name='autores',
            new_name='alunos',
        ),
        migrations.RenameField(
            model_name='tese',
            old_name='nota',
            new_name='avaliacao',
        ),
        migrations.RenameField(
            model_name='tese',
            old_name='pdf',
            new_name='relatorio',
        ),
        migrations.RemoveField(
            model_name='orientador',
            name='teses',
        ),
        migrations.AddField(
            model_name='tese',
            name='entidade_externa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tese',
            name='orientadores',
            field=models.ManyToManyField(related_name='teses', to='teses.orientador'),
        ),
    ]
