# Generated by Django 4.0.6 on 2023-10-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0007_rename_autores_tese_alunos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palavrachave',
            old_name='palavra_chave',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='palavrachave',
            name='tese',
        ),
        migrations.AddField(
            model_name='tese',
            name='palavras_chave',
            field=models.ManyToManyField(related_name='teses', to='teses.palavrachave'),
        ),
    ]
