# Generated by Django 4.0.6 on 2023-10-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0008_rename_palavra_chave_palavrachave_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientador',
            name='apelido',
        ),
    ]
