# Generated by Django 4.0.6 on 2023-10-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0009_remove_orientador_apelido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='tese',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tese',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tese',
            name='tecnologias',
            field=models.ManyToManyField(related_name='teses', to='teses.tecnologia'),
        ),
    ]
