# Generated by Django 4.0.6 on 2023-10-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0010_tecnologia_alter_tese_imagem_alter_tese_resumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tese',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
