# Generated by Django 4.0.6 on 2023-10-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0011_tese_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PalavraChave',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='tese',
            old_name='palavras_chave',
            new_name='areas',
        ),
    ]
