# Generated by Django 4.0.6 on 2023-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0012_rename_palavrachave_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='relatorio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
