# Generated by Django 4.0.6 on 2023-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0013_alter_tese_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='areas',
            field=models.ManyToManyField(blank=True, null=True, related_name='teses', to='teses.area'),
        ),
        migrations.AlterField(
            model_name='tese',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, null=True, related_name='teses', to='teses.tecnologia'),
        ),
    ]
