# Generated by Django 4.0.6 on 2023-10-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0015_alter_tese_imagem_alter_tese_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='teses/'),
        ),
        migrations.AlterField(
            model_name='tese',
            name='relatorio',
            field=models.FileField(blank=True, null=True, upload_to='teses/'),
        ),
    ]
