# Generated by Django 4.0.6 on 2023-10-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0016_alter_tese_imagem_alter_tese_relatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='orientador',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='tecnologia',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='tese',
            options={'ordering': ('titulo',)},
        ),
        migrations.AddField(
            model_name='tese',
            name='palavras_chave',
            field=models.ManyToManyField(blank=True, null=True, related_name='teses', to='teses.palavrachave'),
        ),
    ]
