# Generated by Django 4.0.6 on 2024-06-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0017_palavrachave_alter_area_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tese',
            old_name='numero',
            new_name='numero_TFC',
        ),
    ]
