# Generated by Django 4.0.6 on 2024-06-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0018_rename_numero_tese_numero_tfc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tese',
            old_name='alunos',
            new_name='autores',
        ),
    ]
