# Generated by Django 4.0.6 on 2024-06-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0019_rename_alunos_tese_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='autores',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
