# Generated by Django 4.0.6 on 2024-06-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0020_alter_tese_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='resumo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
