# Generated by Django 4.0.6 on 2024-06-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0021_alter_tese_resumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tese',
            old_name='link',
            new_name='link_aplicacao',
        ),
    ]
