# Generated by Django 4.0.6 on 2024-07-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0022_rename_link_tese_link_aplicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tese',
            name='email_contacto',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
