# Generated by Django 4.0.6 on 2024-07-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0023_tese_email_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ano',
            options={'ordering': ('-ano',)},
        ),
        migrations.AddField(
            model_name='tese',
            name='defesa_dia',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tese',
            name='defesa_hora',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
