# Generated by Django 4.0.6 on 2025-03-26 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teses', '0024_alter_ano_options_tese_defesa_dia_tese_defesa_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='tese',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tese',
            name='areas',
            field=models.ManyToManyField(related_name='teses', to='teses.area'),
        ),
        migrations.AlterField(
            model_name='tese',
            name='palavras_chave',
            field=models.ManyToManyField(related_name='teses', to='teses.palavrachave'),
        ),
        migrations.AlterField(
            model_name='tese',
            name='tecnologias',
            field=models.ManyToManyField(related_name='teses', to='teses.tecnologia'),
        ),
    ]
