# Generated by Django 4.0.6 on 2025-03-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0025_tese_owner_alter_tese_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='ano',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='teses', to='teses.ano'),
        ),
    ]
