# Generated by Django 4.0.6 on 2025-03-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0026_alter_tese_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teses', to='teses.ano'),
        ),
    ]
