# Generated by Django 4.0.6 on 2025-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0028_tese_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='email_contacto',
            field=models.EmailField(default='deisi@ulusofona.pt', max_length=254),
        ),
    ]
