# Generated by Django 4.0.6 on 2025-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0029_alter_tese_email_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='email_contacto',
            field=models.EmailField(max_length=254),
        ),
    ]
