# Generated by Django 4.0.6 on 2025-03-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0031_alter_tese_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='resumo',
            field=models.TextField(),
        ),
    ]
