# Generated by Django 4.0.6 on 2025-03-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0032_alter_tese_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tese',
            name='apresentacao',
            field=models.FileField(blank=True, null=True, upload_to='teses/'),
        ),
    ]
