# Generated by Django 4.0.6 on 2025-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0035_alter_tese_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='imagem',
            field=models.ImageField(default='teses/deisi.png', upload_to='teses/'),
        ),
    ]
