# Generated by Django 4.0.6 on 2025-03-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0036_alter_tese_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='imagem',
            field=models.ImageField(upload_to='teses/'),
        ),
    ]
