# Generated by Django 4.0.6 on 2025-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0037_alter_tese_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tese',
            name='concluido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
