# Generated by Django 5.2 on 2025-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0038_tese_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tese',
            name='relatorio',
            field=models.FileField(blank=True, null=True, upload_to='teses/'),
        ),
    ]
