# Generated by Django 5.2 on 2025-04-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teses', '0039_alter_tese_relatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuida', models.BooleanField(blank=True, default=False, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('entidade_externa', models.CharField(blank=True, max_length=300, null=True)),
                ('resumo', models.TextField()),
                ('imagem', models.ImageField(upload_to='propostas/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='teses.ano')),
                ('areas', models.ManyToManyField(related_name='propostas', to='teses.area')),
                ('cursos', models.ManyToManyField(related_name='propostas', to='teses.curso')),
                ('orientadores', models.ManyToManyField(related_name='propostas', to='teses.orientador')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('palavras_chave', models.ManyToManyField(related_name='propostas', to='teses.palavrachave')),
                ('tecnologias', models.ManyToManyField(related_name='propostas', to='teses.tecnologia')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
    ]
